import { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "../utils/api";

interface FormData {
  title: string;
  description: string;
}

const Newnote: NextPage = () => {
  const [data, setData] = useState<FormData>({
    title: "",
    description: "",
  });

  const handleTitleChange = (event) => {
    // setData({ ...data, title: event.target.value });
  };

  const handleDescriptionChange = (event) => {
    // setData({
    //   ...data,
    //   description: event.target.value,
    // });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1>from to add new note</h1>
        <form
          onSubmit={(event) => {
            handleTitleChange(event);
          }}
        >
          <input type="text" required value={data.title} />
          <textarea
            required
            value={data.description}
            onChange={(event) => {
              handleDescriptionChange(event);
            }}
          />
        </form>
      </main>
    </>
  );
};

export default Newnote;
